let autos = [
            {   
                id:0,
                marca: "Volkswagen",
                modelo: "Scirocco GTS",
                anio: 2016,
                color: "Negro",
                imagen:"/images/products/sirocco.jpeg",
                descripcion:"Auto depotivo.  Trae el conocido motor del anterior Scirocco 2.0 TSi: turbo, con 211 cv y 280 Nm. Caja secuencial de doble embrague (DSG) de seis velocidades. Tracción delantera.",
                comentarios:1,
            },
            {
                id:1,
                marca: "Volkswagen",
                modelo: "Golf GTI",
                anio: 2020,
                color: "white",
                imagen:"/images/products/golf.jpeg",
                descripcion:" La nueva generación del Volkswagen Golf GTI cuenta con un aspecto más achatado, alargado y dinámico en comparación con los predecesores. Los diseñadores han reformado todas las piezas de la carrocería y las han perfeccionado con los expertos de aerodinámica en el túnel de viento. Se destaca por contar con muecas características, tales como la clásica vira en color rojo sobre la parrilla, con la inscripción GTI en uno de sus extremos.En el manejo, el Golf GTI de octava generación dispone de un sistema de dinámica avanzada, en el que tanto el ESP, como el bloqueo electrónico del diferencial se conjugan para entregar una conducción segura y adaptada al tipo de manejo seleccionado por el conductor. Asimismo, de manera opcional, puede contar con suspensión adaptativa, que mediante un sistema electromecánico, puede hacer variar la dureza de la suspensión. En casi 45 años de historia, el Golf GTI se convirtió en el deportivo compacto de mayor éxito alrededor del mundo, del que ya se han fabricado más de 2,3 millones de unidades hasta finales de 2019. Siempre bajo un concepto similar: crear un auto de tracción delantera ágil, con tren de rodaje deportivo, ergonomía perfecta y diseño elegante.",
                comentarios:2,
            },
            {
                id:2,
                marca: "Volkswagen",
                modelo: "Vento GLI ",
                anio: 2014,
                color: "Azul",
                imagen:"/images/products/vento.jpeg",
                descripcion: "El corazón de este Vento GLI es un motor naftero de cuatro cilindros, 2.0 litros turbo, con inyección directa, que eroga una potencia de 230 CV y un torque de 350 Nm entre las 1.500 y 4.000 rpm. Se trata de un impulsor con una potencia 19 CV mayor al último GLI lanzado en la Argentina y con nada más y nada menos que 80 CV más que el resto de la gama que equipa el motor TSi de 1.4 litros y 150 CV. Se asocia a una de las transmisiones automáticas que más nos gusta manejar, se trata de la confiable DSG, de doble embrague y 6 velocidades.",
                comentarios:3,
            },
            {
                id:3,
                marca: "Volkswagen",
                modelo: "Amarok V6 Dark Lable",
                anio: 2020,
                color: "Negra",
                imagen:"/images/products/amarokv6.jpeg",
                descripcion:"La nueva VW Amarok V6 258cv Black Style será recordada en Autoblog por haber protagonizado una doble paradoja. Es el vehículo de pruebas que estuvo más semanas en nuestro garage y, al mismo tiempo, el que proporcionalmente menos pudimos manejar: apenas dos días. Se explicó todo en esta nota.La Amarok V6 258cv Black Style tiene un precio de 3.8 millones de pesos, aunque también se ofrecen versiones V6 258cv desde 2.97 millones. La crítica abreviada se reproduce a continuación.¿Cómo se diferencia la anterior Amarok V6 224cv de la nueva Amarok V6 258cv? Por fuera, en las versiones Comfortline, Highline y Extreme (todas ahora con 258cv), no hay forma de saberlo. Habrá que guiarse -más o menos- por el número de la patente. VW podría haber colocado algún emblema, para que los propietarios luzcan la novedad con cierto orgullo, pero no lo hizo.",
                comentarios:4,
            },
            {
                id:4,
                marca: "Audi",
                modelo: "TT RS",
                anio: 2019,
                color: "Blanco",
                imagen:"/images/products/auditt.jpeg",
                descripcion:"El Audi TT RS Coupé TFSI 294 kW (400 CV) quattro S tronic (2019-2021) tiene un motor gasolina de 2480cc con 5 cilindros ubicados en línea que alcanza una potencia máxima de 400CV a 5850-7000rpm y par máximo de 480Nm a 1700-5850rpm. Se trata por tanto de una mecánica con una potencia concreta de 400CV, con alimentación inyección mixta directa/indirecta. Esta mecánica de 2480cc de cilindrada consigue unos consumos de 10.5 litros en circulación urbana, 6.4 en carretera y consumo de 7.9 litros a los 100km de media. Con esto los niveles de emisiones se sitúan en 181 gramos de CO2 por kilómetro.",
                comentarios:5,
            },
            {
                id:5,
                marca: "Audi",
                modelo: "A6 S",
                anio: 2016,
                color: "Rojo",
                imagen:"/images/products/audia6.jpeg",
                descripcion:" El Audi A6 es la berlina mediana grande de Ingolstadt, un modelo que lleva fabricándose desde 1994 a lo largo de cuatro generaciones, la última de las cuales se presentó en la primavera de 2014. A parte de la Berlina cuenta con una versión familiar (Avant), otra de aspecto todocamino (Allroad), una deportiva (A6 S) e hiperdeportiva (RS 6) y una versión híbrida. La gama de motores para el nuevo A6 incluye tres mecánicas TFSI con potencias de entre 190 CV y 333 CV y cinco motores TDI que van de los 150 CV a los 320 CV. La tracción puede ser delantera o a las cuatro ruedas (Quattro). El Audi RS 6 Avant es la versión más potente de la gama A6. Está disponible únicamente con carrocería familiar y con dos niveles de potencia: 560 CV (RS 6 Avant, disponible desde finales de 2014) y 605 CV (RS 6 Avant performance, disponible desde finales de octubre de 2015). La tracción es siempre en las cuatro ruedas y el cambio automático de ocho velocidades. Como en toda la gama Audi, a la hora de comprar nuestro nuevo vehículo podremos optar entre los niveles de acabado Ambiente, Attraction y S (Sport). El precio de partida para el A6 arranca en 41.130 euros del motor 2.0 TDI Ultra de 150 CV.",
                comentarios:6,
            },
            {
                id:6,
                marca: "Audi",
                modelo: "Q5 RS",
                anio: 2018,
                color: "Negro",
                imagen:"/images/products/audiq5.jpeg",
                descripcion:"Tras la presentación del Audi SQ5 a principios de año, Audi ya está ultimando los detalles de puesta a punto de la versión más deportiva y radical de su todocamino: el futuro Audi RS Q5 2018. A priori, este este nuevo SUV, que podría estar presente en el próximo salón de Frankfurt, en el mes de septiembre, equiparía un propulsor conocido: la mecánica de gasolina 2.9 V6 biturbo, que emplea el novedoso Audi RS 5 Coupé, con 450 CV de potencia y 600 Nm de par máximo. Por supuesto, estaría asociada a la transmisión automática con convertidor de par Tiptronic, con levas tras el volante y ocho velocidades.",
                comentarios:7,
            },
       
            {
                id:7,
                marca: "Chevrolet",
                modelo: "Camaro SS",
                anio: 2015,
                color: "Amarillo",
                imagen:"/images/products/camaro.jpeg",
                descripcion:"La gracia de tener un muscle-car no pasa tanto por el diseño exterior ni por el equipamiento interior. Lo que divide las aguas en este segmento, siempre, es lo que hay bajo el capot. Y acá Chevrolet no defrauda: porque ahí adentro hay un V8 L99, perteneciente al legendario linaje de los Small Blocks de General Motors. Claro que, desde el punto de vista argentino, no tiene nada de small. Es un colosal 6.2 litros con sólo dos válvulas por cilindro e inyección electrónica indirecta, que rinde homenaje al viejo lema: “There’s no replacement for displacement” (“No hay reemplazo para la cilindrada”). Y rinde como corresponde: potencia máxima de 405 cv a 5.900 rpm y un torque de 556 Nm a 4.300 rpm. La única transmisión disponible en la Argentina es automática. Es una caja secuencial de seis velocidades, con levas al volante y tres modos: Automático, Secuencial y Manual. La tracción, como no podía ser de otra manera, es trasera.",
                comentarios:8,
            },    
          ]



module.exports = autos;